### ISSUE TITLE
Add Foreign Key Details

### ISSUE THREAD

**Issue by nasrulhazim** [cleaniquecoders/laravel-db2doc#4]
Reference: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.8/reference/schema-manager.html

**Comment by ilyasfoo** [comment]
@nasrulhazim Please review #5

**Comment by nasrulhazim** [comment]
@ilyasfoo , PR approved.

Initially my intention to create something like this:

![tangkapan skrin 2018-08-17 pada 7 00 59 ptg](https://user-images.githubusercontent.com/10341422/44263312-fec1d780-a250-11e8-9453-d8d3a43bc2df.png)

But as for now, #5 should be good enough.
